### PR TITLE
Directory restructured and an issue template added.

### PR DESCRIPTION
**Pull request by amanabt**
**Purpose:**
- Writing an issue template for Quazartech.
- Creating a new directory structure for the Style-Guidelines repository.

**Changes**
- The code_guidelines for Python has been shifted to `code_guidelines/python.md` as mentioned
  in the issue #1 .
- Adding a new directory `github`. This directory will contain all the guidelines related to github, like
  pull request guidelines/templates, issue guidelines/templates etc.
- An issue template has been created in the file `github/issue_template.md`. This file contains two types 
  of issue template, one for reporting `bugs` and other for a `new feature request`.

**Sources**
I have taken help from these sources for making the issue template for our organization.
- [Meteor Guidelines](https://github.com/meteor/meteor) guidelines.

### CODE REVIEW

**Review by shyams2 — COMMENTED** [review]
The issue guidelines seem pretty thorough. However, to me, it seems to be a bit of an overkill. It makes good sense to have this pattern followed when a user stumbles across a bug/feature request.

I propose adding a clause for developers of the code, where bugs/upcoming features can be tracked with a more minimalist description.

**Comment by amanabt** [comment]
@ShyamSS-95 

Inside the `Bug` section, the new subsections for me were these:
- Checklist (incomplete, need more input from developers)
- Reproducibility (Compulsory for both user and developer)
- Possible Fix (Optional for both user and developer)

I think that the template for the `Feature Request` is short and minimalist. 

I don't agree with your point that the developers and users(people unfamiliar with the code) should have
different issue templates. I think that a thorough issue template is necessary to easily keep track of the issues over a long period of time.

However, if you want to make the proposed issue template more minimalistic, I request you to tell me
exactly what you want to remove from the `Bug` issue template?

**Comment by gitansh95** [comment]
@amanabt, I think what @ShyamSS-95 is saying is if a developer of some code repository finds a bug in his/her own code while using it, should that bug be logged as an issue in the extensive format given above, or should there be a separate shorter version of an issue template just for owner devs?

**Comment by amanabt** [comment]
@gitansh95 @ShyamSS-95 
I have updated my previous comment, please have a look at it.

@gitansh95 
>**Question Asked:** if a developer of some code repository finds a bug in his/her own code while using it, should that bug be logged as an issue in the extensive format given above, or should there be a separate shorter version of an issue template just for owner devs?

I think that it depends on the nature of the bug which a developer finds. If the bug is a trivial one
then the developer might choose to just fix it him/herself without opening an issue at all.
But, if the issue is not that trivial and the developer thinks that an issue should be opened for
that bug, then it is necessary to be thorough with the issue and I would recommend him/her to
follow the proposed `issue template`.
This is necessary because if in future, somebody finds a similar bug somewhere else in the code
or in some entirely different code, then, a thorough issue could help him/her get a solution much 
more quickly, compared to a scenario when he/she finds a badly written issue and has trouble
understanding it.

We should also not forget that our issue can help people in general on the internet. Like we take help
from `StackOverflow` and sometimes from `GitHub` issues from an entirely unrelated code. At Quazar
we should try to follow high standards for those sections of people too.

**Comment by shyams2** [comment]
@amanabt 
Hmm... OK. Let me elaborate with an example. Update issue #1 using the format that you've proposed.
While your current information is sufficient, it isn't compliant with the format you intend to follow. Please implement the same and let me know if it doesn't feel unnecessary to you.

Also, the whole point of adding issues in addition to having an accurate tracking is to make users aware of the fact that there is a bug in the current version of the code. So, with that thought in mind, it's necessary for every bug(even trivial ones) to be reported.

My thought is that we amend the page something along the line of this:
```
While more trivial issues may be reported stating the anomalous behaviour observed(more 
particular to developers) and the PR used to close it(please use your judgement to provide
sufficient information), we suggest that you follow the issue given below for the sake of clarity: 

# **Issue Template**
 +
 +## Bug
 +Use this template when reporting a bug.
 +
 +#### Short description of the bug
 +
....
```
Also, let take the case of issues that are opened by developers of ArrayFire. A feature request goes something along the lines of [this](https://github.com/arrayfire/arrayfire/issues/1896) and [this](https://github.com/arrayfire/arrayfire/issues/1875).
While this is the format they use for resolving bugs:[1](https://github.com/arrayfire/arrayfire/issues/1529), [2](https://github.com/arrayfire/arrayfire/issues/1457), [3](https://github.com/arrayfire/arrayfire/issues/1356),[4](https://github.com/arrayfire/arrayfire/issues/1702)

You can observe that they provide enough information to keep track and reproduce the bugs wherever applicable. I think this is the approach that we should be taking. Now, if a new user(one unfamiliar with the code) has an issue with the code, it is understandable to have the issues reported in the format you've proposed since it's more thorough and will help us identifying and fixing the bug more quickly.

**Comment by amanabt** [comment]
@ShyamSS-95 
Thanks for pointing out that the issue #1 was not compliant with the guidelines I stated. I hope that you realize that this issue was opened before I wrote down the issue guidelines. However, I have rewritten the issue guidelines compliant with the issue guidelines for a `new feature request` with slight changes in just the terminologies, keeping the overall structure same, and I found out that the issue has now become more organized. So, maybe the template could be implemented even on trivial issues. I also realized that while following the guidelines I was easily able to think what to write about the issue and how to organize it.
It is important to note that my earlier version of the issue #1 was roughly following the guidelines but everything was messed up in a single, badly written paragraph.

I think that you are mistaken in thinking that "the major point in adding issues is to make users aware of the fact that there is a bug in the current version of the code". The whole point of keeping issues is to keep track of the bugs we have and have discussions to resolve them. In fact, this is the official GitHub page [About Issues](https://help.github.com/articles/about-issues/), I would suggest you go to this page and read it. If you want to just notify the users that there are bugs in the code you can do that in a single separate file, of course, issues are an indication as well, but definitely, this is not one their primary purpose.

Coming to your template, I don't think the template you have proposed can be called a template. It has just one section! The point of having a template, especially in an open source project is to reduce the entropy and also to help guide inexperienced people to easily write an issue or something else. Of course, I do not deny that there won't be any exceptions, but we should try to minimize the entropy.

I think that the examples you have provided are really bad. If you want to have a look at good examples of the issues, have a look at the [Meteor Issues](https://github.com/meteor/meteor/issues) or [Problems with Linux Kernel](http://linuxtesting.org/results/ldv)

**Comment by mchandra** [comment]
Hi All,

I think everyone has raised good points. Let us first outline possible use cases for issues while we are deciding on the template. Note that the template itself is rolling and can change. That is why the guidelines are themselves a repository. We can try something out and see how well it works.

Use cases:

1. For developers to keep track of various bugs that one encounters as one is using and working with the code. The issue acts like a post-it note that reminds them that there is a bug that needs to be addressed. From my own experience (I have been guilty of this), developers tend not to report issues that they encounter because they assume that they will fix it immediately and then there's no point of the issue being opened.

2. For developers to keep track of things that they want to implement.

3. For users to report bugs to developers.

4. For users to request features.

5. For users to ask questions to developers.

Do we first all agree to the above? Please feel free to list out any and all possible use cases.

**Comment by amanabt** [comment]
@mchandra 
I agree with your points.

**Comment by amanabt** [comment]
1.

**Comment by amanabt** [comment]
sorry, clicked on the `close and comment` button by mistake

**Comment by gitansh95** [comment]
@mchandra I agree with the possible use cases.

**Comment by mchandra** [comment]
I think we should first address use cases (1) and (2) right now. 

Case (1):
A possible quick, and easy format for this:
```
#### commit : 

#### Issue : 
```
The description should contain essential details and any info the developer thinks is essential. My primary concern at the moment is people not opening issues to self-report bugs. Should we incentivize this?

Case (2):
This needs to be a little more detailed:
```
#### Description (what this code should do):

#### Motivation (why is it needed):

#### Possible implementation:
```

**Comment by amanabt** [comment]
@mchandra 
Should I change my issue template to the template suggested by you?

**Comment by mchandra** [comment]
lets wait for more feedback on this.

**Comment by shyams2** [comment]
The format is agreeable to me. However, I don't think that incentivizing issue opening is the right step to take.

**Comment by mchandra** [comment]
Alright, lets follow the format in my last message for now. We can always modify as and when needed. 

@amanabt could you edit and close this PR? Thanks.

**Comment by amanabt** [comment]
@mchandra New issue template added. Closing the PR #2

**Pull request merged**
